export const CHANGE_FORM_TITLE = 'CHANGE_FORM_TITLE';
export const CHANGE_FORM_PRICE = 'CHANGE_FORM_PRICE';
export const CHANGE_FILTER_VALUE = 'CHANGE_FILTER_VALUE';
export const CHANGE_EDITED_ID = 'CHANGE_EDITED_ID';

export const ADD_NOTE_ARR = 'ADD_NOTE_ARR';
export const REMOVE_NOTE_ARR = 'REMOVE_NOTE_ARR';
export const CHANGE_NOTE_ARR = 'CHANGE_NOTE_ARR';
export const FITLER_NOTE_ARR = 'FITLER_NOTE_ARR';

export default {
  CHANGE_FORM_TITLE,
  CHANGE_FORM_PRICE,
  CHANGE_FILTER_VALUE,
  CHANGE_EDITED_ID,
  ADD_NOTE_ARR,
  REMOVE_NOTE_ARR,
  CHANGE_NOTE_ARR,
  FITLER_NOTE_ARR
};